services:
  mysqldb:
    image: "mysql"
    container_name: mysqldb
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Kota@2020
      MYSQL_DATABASE: EMS
      MYSQL_USER: root
      MYSQL_PASSWORD: Kota@2020
    ports:
      - "3306:3306"
#    networks:
#      - backend

  spring-app:
    image: "karanjit708/employee_management_system_backend101:latest"
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
    container_name: backend_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/EMS?useSSL=false&&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Kota@2020
    volumes:
      - /logs:/logs
#    networks: # Networks to join (Services on the same network can communicate with each other using their name)
#      - backend
#      - frontend

#   reactjs:
#     image: "shubhanshi/mefrontend:v3"
#     restart: always
#     container_name: frontend_container
# #    depends_on:
# #      - spring-app
# #    command:
# #      - npm start
#     ports:
#       - "3000:3000"
# #    networks:
# #      - frontend

volumes:
  mysql-data:
    driver: local

#networks:
#  backend:
#  frontend: