services:
  # mysqldb:
  #   image: "mysql"
  #   container_name: mysqldb
  #   restart: always
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Kota@2020
  #     MYSQL_DATABASE: EMS
  #     # MYSQL_USER: root
  #     # MYSQL_PASSWORD: Kota@2020
  #   ports:
  #     - "3306:3306"
  
  
  frontend:
    image: karanjit708/frontend:latest
    restart: always
    container_name: frontend
    # environment:
    #   PORT: 3000
      # PROXY_API: http://playground-web-backend:8080/
    ports:
      - "3000:3000"
    networks:
      - my-network
  
  
  spring-app:
    image: "karanjit708/backend:latest"
    #"karanjit708/employee_management_system_backend101:latest"
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/EMS?useSSL=false&&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Kota@2020
    volumes:
      - /logs:/logs
    networks:
      - my-network

volumes:
  mysql-data:
    driver: local

networks:
  my-network:
    driver: bridge

